export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';

export const LOAD_BILLS_SUCCESS = 'LOAD_BILLS_SUCCESS';
export const CREATE_BILL_SUCCESS = 'LOAD_BILLS_SUCCESS';
export const UPDATE_BILL_SUCCESS = 'LOAD_BILLS_SUCCESS';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';




